AWSTemplateFormatVersion: '2010-09-09'
Description: "Create an EC2 server with Security Group using CloudFormation (only if t2.micro)"

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: Enter EC2 Instance Type
    AllowedValues: 
      - t2.micro
      - t2.small
      - t2.medium
      - t3.micro
    ConstraintDescription: must be a valid EC2 instance type from the list above

Conditions:
  CreateInstance: !Equals [!Ref InstanceType, t2.micro]

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Condition: CreateInstance        
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-00af95fa354fdb788
      SecurityGroupIds:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "MyEC2Instance-${InstanceType}"

Outputs:
  InstanceId:
    Description: The EC2 instance ID
    Value: !If [CreateInstance, !Ref MyEC2Instance, "Instance not created"]

